version: "3.9"

services:
  web:
    image: acgfaka
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8082:80"
    volumes:
      - ./runtime:/var/www/html/runtime

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: acgfaka
      MYSQL_USER: acgfaka
      MYSQL_PASSWORD: acgfaka_password
    volumes:
      - ./mysql:/var/lib/mysql

  redis:
    image: redis:alpine
    restart: always